services:
  dragonwilds:
    build: .
    container_name: dragonwilds-server
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "7777:7777/udp"
    env_file:
      - .env
    volumes:
      - server-files:/opt/dragonwilds
      - savegames:/opt/dragonwilds/RSDragonwilds/Saved/Savegames
      - logs:/opt/dragonwilds/RSDragonwilds/Saved/Logs
    mem_limit: 8g

volumes:
  server-files:
  savegames:
  logs:
